- name: SSH - Creates .ssh directory
  ansible.builtin.file:
    path: "~/.ssh"
    state: directory
    mode: "0755"

- name: SSH - Create files
  ansible.builtin.include_tasks: ssh.yml
  loop: "{{ ssh_keys }}"

- name: SSH - Create config file
  ansible.builtin.template:
    src: config.j2
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    owner: "{{ ansible_env.USER }}"

- name: Secrets - Create keys file
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.keys"
    content: |
      {{ lookup('ansible.builtin.unvault', 'secrets/keys') }}
    mode: "0644"
    owner: "{{ ansible_env.USER }}"
