---
- name: Configure macOS
  hosts: all

  vars_files:
    - default.config.yml

  vars_prompt:
    - name: become_pass
      prompt: Sudo password?
      private: true

  gather_facts: true

  roles:
    - role: brew
    - role: apple_store
    - role: zsh
    - role: ssh
    - role: git
    - role: java
    - role: configure_macos
    - role: dock
    - role: cursor
    - role: node
