---
- name: "Check node version: {{ node_version }}"
  shell: source $(brew --prefix nvm)/nvm.sh && nvm ls {{node_version}}
  register: node_v_result
  changed_when: "node_version|string not in node_v_result.stdout"
  ignore_errors: true
  no_log: true

- set_fact: version_installed="{{ node_v_result is success }}"

- name: "Installing node version: {{ node_version }}"
  shell: source $(brew --prefix nvm)/nvm.sh && nvm install {{node_version}}
  when: not version_installed
