- name: "Check node version: {{ node_version }}"
  shell: source $(brew --prefix nvm)/nvm.sh && nvm ls {{node_version}}
  register: node_v_result
  ignore_errors: true
  changed_when: false

- name: "Check if node version is installed"
  set_fact:
    version_installed: "{{ node_v_result.rc == 0 and node_version|string in node_v_result.stdout }}"

- name: "Installing node version: {{ node_version }}"
  shell: source $(brew --prefix nvm)/nvm.sh && nvm install {{node_version}}
  when: not version_installed
