---
- name: Git - name
  community.general.git_config:
    scope: global
    name: user.name
    value: '{{ git.name }}'

- name: Git - email address
  community.general.git_config:
    scope: global
    name: user.email
    value: '{{ git.email }}'

- name: Git - override default branch to match with GitHub defaults
  community.general.git_config:
    scope: global
    name: init.defaultBranch
    value: main